export interface Commanders {
  name: string;
}
export const Commander: Commanders[] = [
  { name: "Aamon" },
  { name: "Abe" },
  { name: "Angela" },
  { name: "Asta" },
  { name: "Aurora" },
  { name: "Bersi" },
  { name: "Brown" },
  { name: "Buss" },
  { name: "Chou" },
  { name: "Connie" },
  { name: "Dubi" },
  { name: "Eggie" },
  { name: "Eva" },
  { name: "Fanny" },
  { name: "Guinevere" },
  { name: "Harper" },
  { name: "Johnson" },
  { name: "Kagura" },
  { name: "Lancelot" },
  { name: "Layla" },
  { name: "Ling" },
  { name: "Lukas" },
  { name: "Lylia" },
  { name: "Mavis" },
  { name: "Miya" },
  { name: "Moskov" },
  { name: "Nana" },
  { name: "Pao" },
  { name: "Popol & Kupa" },
  { name: "Ragnar" },
  { name: "Rya" },
  { name: "Vale" },
  { name: "Wanwan" },
  { name: "Yuki" },
  { name: "Zilong" },
];

export interface Heroes {
  name: string;
  cost: number;
  synergy: string;
}

export const Hero: Heroes[] = [
  { name: "Akai", cost: 2, synergy: "Dragon Altar, Dauntless" },
  { name: "Aldous", cost: 2, synergy: "Dawnbringer, Bruiser" },
  { name: "Alpha", cost: 5, synergy: "Shadeweaver, Weapon Master" },
  { name: "Angela", cost: 2, synergy: "Faeborn, Mage" },
  { name: "Argus", cost: 4, synergy: "Doomsworn, Weapon Master" },
  { name: "Atlas", cost: 1, synergy: "Northern Vale, Defender" },
  { name: "Aurora", cost: 5, synergy: "Northern Vale, Mage" },
  { name: "Badang", cost: 1, synergy: "Emberlord, Bruiser" },
  { name: "Balmond", cost: 2, synergy: "Emberlord, Dauntless" },
  { name: "Chang'e", cost: 3, synergy: "Dragon Altar, Stargazer" },
  { name: "Clint", cost: 3, synergy: "Shadeweaver, Marksman" },
  { name: "Cyclops", cost: 1, synergy: "Doomsworn, Stargazer" },
  { name: "Diggie", cost: 2, synergy: "Eruditio, Support" },
  { name: "Dyrroth", cost: 3, synergy: "Doomsworn, Bruiser" },
  {
    name: "Esmeralda",
    cost: 3,
    synergy: "Faeborn, Support, Dauntless",
  },
  { name: "Franco", cost: 5, synergy: "Doomsworn, Dauntless" },
  { name: "Freya", cost: 3, synergy: "Northern Vale, Weapon Master" },
  { name: "Gord", cost: 4, synergy: "Emberlord, Mage" },
  { name: "Granger", cost: 2, synergy: "Exorcist, Marksman" },
  { name: "Guinevere", cost: 4, synergy: "Faeborn, Bruiser" },
  { name: "Gusion", cost: 2, synergy: "Dawnbringer, Swordsman" },
  { name: "Hayabusa", cost: 4, synergy: "Exorcist, Swordsman" },
  { name: "Helcurt", cost: 1, synergy: "Shadeweaver, Swordsman" },
  { name: "Hylos", cost: 2, synergy: "Doomsworn, Defender" },
  { name: "Irithel", cost: 4, synergy: "Doomsworn, Marksman" },
  { name: "Johnson", cost: 3, synergy: "Eruditio, Defender" },
  { name: "Kagura", cost: 3, synergy: "Exorcist, Mage" },
  { name: "Kaja", cost: 4, synergy: "Emberlord, Defender, Support" },
  { name: "Karina", cost: 3, synergy: "Astro Power, Swordsman" },
  { name: "Layla", cost: 2, synergy: "Eruditio, Marksman" },
  { name: "Ling", cost: 4, synergy: "Dragon Altar, Swordsman" },
  { name: "Lolita", cost: 1, synergy: "Eruditio, Dauntless" },
  { name: "Lunox", cost: 4, synergy: "Astro Power, Stargazer" },
  { name: "Luo Yi", cost: 2, synergy: "Shadeweaver, Stargazer" },
  { name: "Martis", cost: 2, synergy: "Astro Power, Weapon Master" },
  { name: "Masha", cost: 2, synergy: "Northern Vale, Bruiser" },
  { name: "Minotaur", cost: 5, synergy: "Astro Power, Defender" },
  { name: "Moskov", cost: 5, synergy: "Emberlord, Marksman" },
  { name: "Natan", cost: 5, synergy: "Eruditio, Stargazer" },
  { name: "Nolan", cost: 4, synergy: "Eruditio, Swordsman" },
  { name: "Odette", cost: 3, synergy: "Astro Power, Mage" },
  { name: "Popol & Kupa", cost: 3, synergy: "Northern Vale, Summoner" },
  { name: "Sun", cost: 5, synergy: "Dragon Altar, Summoner" },
  { name: "Suyou", cost: 2, synergy: "Dragon Altar, Weapon Master" },
  { name: "Terizla", cost: 4, synergy: "Dawnbringer, Defender" },
  { name: "Thamuz", cost: 3, synergy: "Emberlord, Weapon Master" },
  { name: "Uranus", cost: 3, synergy: "Dawnbringer, Dauntless" },
  { name: "Vale", cost: 1, synergy: "Dawnbringer, Mage" },
  { name: "Vexana", cost: 4, synergy: "Dawnbringer, Summoner" },
  { name: "Wanwan", cost: 1, synergy: "Dragon Altar, Marksman" },
  { name: "Yu Zhong", cost: 5, synergy: "Exorcist, Bruiser" },
  { name: "Yve", cost: 4, synergy: "Northern Vale, Stargazer" },
  { name: "Zhask", cost: 1, synergy: "Astro Power, Summoner" },
];

export interface Cards {
  name: string;
  colour: string;
}

export const Card: Cards[] = [
  { name: "Attack & Defend I", colour: "Blue" },
  { name: "Barrier's Seal I", colour: "Blue" },
  { name: "Breath of Berserk I", colour: "Blue" },
  { name: "Cyclical Support", colour: "Blue" },
  { name: "Dark Blade", colour: "Blue" },
  { name: "Excellent Recruit", colour: "Blue" },
  { name: "Glittering Jewels I", colour: "Blue" },
  { name: "Healing Fountain", colour: "Blue" },
  { name: "Heroes Assemble", colour: "Blue" },
  { name: "Jump the Gun", colour: "Blue" },
  { name: "Jump the Gun+", colour: "Blue" },
  { name: "Magic Immersion I", colour: "Blue" },
  { name: "Ocean Treasure", colour: "Blue" },
  { name: "Prime Selection", colour: "Blue" },
  { name: "Purest Power I", colour: "Blue" },
  { name: "Rock Solid", colour: "Blue" },
  { name: "Rogue's Aid", colour: "Blue" },
  { name: "Solid Alliance I", colour: "Blue" },
  { name: "Steady Growth I", colour: "Blue" },
  { name: "Thickened Blood I", colour: "Blue" },
  { name: "Uncertain Fortune", colour: "Blue" },
  { name: "Unlimited Expansion I", colour: "Blue" },
  { name: "Adequate Stock", colour: "Purple" },
  { name: "Airdrop Command", colour: "Purple" },
  { name: "All-around Warrior II", colour: "Purple" },
  { name: "Apex Weapons", colour: "Purple" },
  { name: "Astro Power Badge", colour: "Purple" },
  { name: "Attack & Defend II", colour: "Purple" },
  { name: "Barrier's Seal II", colour: "Purple" },
  { name: "Blood Claw", colour: "Purple" },
  { name: "Bounty Hunt", colour: "Purple" },
  { name: "Breath of Berserk II", colour: "Purple" },
  { name: "Bright Sunshine", colour: "Purple" },
  { name: "Bruiser's Badge", colour: "Purple" },
  { name: "Celestial Embrace", colour: "Purple" },
  { name: "Combat Training I", colour: "Purple" },
  { name: "Coronation", colour: "Purple" },
  { name: "Counteraction", colour: "Purple" },
  { name: "Dawnbringer's Badge", colour: "Purple" },
  { name: "Dauntless' Badge", colour: "Purple" },
  { name: "Defeat's Dividend", colour: "Purple" },
  { name: "Defender's Badge", colour: "Purple" },
  { name: "Demon Commander", colour: "Purple" },
  { name: "Doomsworn's Badge", colour: "Purple" },
  { name: "Dragon Veil", colour: "Purple" },
  { name: "Dragon Altar's Badge", colour: "Purple" },
  { name: "Elite Team", colour: "Purple" },
  { name: "Emberlord's Badge", colour: "Purple" },
  { name: "Enlightenment", colour: "Purple" },
  { name: "Eternal Knowledge", colour: "Purple" },
  { name: "Eternity", colour: "Purple" },
  { name: "Equipment Vault", colour: "Purple" },
  { name: "Eruditio's Badge", colour: "Purple" },
  { name: "Fast Promotion", colour: "Purple" },
  { name: "Fateful Dice", colour: "Purple" },
  { name: "Fortified Defense", colour: "Purple" },
  { name: "Frontier Blitz", colour: "Purple" },
  { name: "Full Throttle", colour: "Purple" },
  { name: "Fully Loaded", colour: "Purple" },
  { name: "Glittering Jewels II", colour: "Purple" },
  { name: "Heroic Arrival", colour: "Purple" },
  { name: "Howling Wind", colour: "Purple" },
  { name: "Leaf & Flower", colour: "Purple" },
  { name: "Magic Immersion II", colour: "Purple" },
  { name: "Magic Surge", colour: "Purple" },
  { name: "Magical Training I", colour: "Purple" },
  { name: "Manic Slam", colour: "Purple" },
  { name: "Marksman's Badge", colour: "Purple" },
  { name: "Northern Vale's Badge", colour: "Purple" },
  { name: "Pas de Deux", colour: "Purple" },
  { name: "Payday", colour: "Purple" },
  { name: "Premium Client I", colour: "Purple" },
  { name: "Purest Power II", colour: "Purple" },
  { name: "Reinforcement", colour: "Purple" },
  { name: "Reinforcement+", colour: "Purple" },
  { name: "Rising Festivities", colour: "Purple" },
  { name: "Rogue Mercenary", colour: "Purple" },
  { name: "Snowstorm", colour: "Purple" },
  { name: "Solid Alliance II", colour: "Purple" },
  { name: "Stargazer's Badge", colour: "Purple" },
  { name: "Steady Growth II", colour: "Purple" },
  { name: "Steel Front", colour: "Purple" },
  { name: "Swordsman's Badge", colour: "Purple" },
  { name: "Talisman Unleashed", colour: "Purple" },
  { name: "Team Mission", colour: "Purple" },
  { name: "Thickened Blood II", colour: "Purple" },
  { name: "The Book of War", colour: "Purple" },
  { name: "Total Domination", colour: "Purple" },
  { name: "Transfer Initiative", colour: "Purple" },
  { name: "Unlimited Expansion II", colour: "Purple" },
  { name: "Unyielding Spirit", colour: "Purple" },
  { name: "Victory Horn II", colour: "Purple" },
  { name: "Weapon Master's Badge", colour: "Purple" },
  { name: "Winner's Mark", colour: "Purple" },
  { name: "Ally's Call", colour: "Orange" },
  { name: "Astro Power's Blessing", colour: "Orange" },
  { name: "Box of Holy Objects", colour: "Orange" },
  { name: "Breath of Berserk III", colour: "Orange" },
  { name: "Bruiser's Blessing", colour: "Orange" },
  { name: "Combat Training II", colour: "Orange" },
  { name: "Dawnbringer's Blessing", colour: "Orange" },
  { name: "Dauntless' Blessing", colour: "Orange" },
  { name: "Defender's Blessing", colour: "Orange" },
  { name: "Doomsworn's Blessing", colour: "Orange" },
  { name: "Dragon Altar's Blessing", colour: "Orange" },
  { name: "Emberlord's Blessing", colour: "Orange" },
  { name: "Ethereal Essence", colour: "Orange" },
  { name: "Eruditio's Blessing", colour: "Orange" },
  { name: "Fortified", colour: "Orange" },
  { name: "Frontline Support", colour: "Orange" },
  { name: "Fully Armed", colour: "Orange" },
  { name: "Golden Era", colour: "Orange" },
  { name: "Golden Era+", colour: "Orange" },
  { name: "Last Resort", colour: "Orange" },
  { name: "Magic Immersion III", colour: "Orange" },
  { name: "Magical Training II", colour: "Orange" },
  { name: "Marksman's Blessing", colour: "Orange" },
  { name: "Novel Equipment", colour: "Orange" },
  { name: "Northern Vale's Blessing", colour: "Orange" },
  { name: "Opening Promotion", colour: "Orange" },
  { name: "Party's Opening", colour: "Orange" },
  { name: "Peculiar Merchant", colour: "Orange" },
  { name: "Premium Client II", colour: "Orange" },
  { name: "Satan's Whisper", colour: "Orange" },
  { name: "Sharp Arrow", colour: "Orange" },
  { name: "Stargazer's Blessing", colour: "Orange" },
  { name: "Strategizing", colour: "Orange" },
  { name: "Surprise Splash", colour: "Orange" },
  { name: "Swordsman's Blessing", colour: "Orange" },
  { name: "Technological Revolution", colour: "Orange" },
  { name: "Technological Revolution+", colour: "Orange" },
  { name: "Territory Agreement", colour: "Orange" },
  { name: "The Hunt", colour: "Orange" },
  { name: "The More, the Merrier", colour: "Orange" },
  { name: "Thickened Blood III", colour: "Orange" },
  { name: "Untamed Soul", colour: "Orange" },
  { name: "Vault Upgrade", colour: "Orange" },
  { name: "Vault Upgrade+", colour: "Orange" },
  { name: "Victory Horn III", colour: "Orange" },
  { name: "Victory Horn III+", colour: "Orange" },
  { name: "Weapon Master's Blessing", colour: "Orange" },
  { name: "Yesterday Once More", colour: "Orange" },
];

export interface Equipments {
  name: string;
  type: string;
}

export const Equipment: Equipments[] = [
  { name: "DemonHunterSword", type: "Physical" },
  { name: "GoldenStaff", type: "Physical" },
  { name: "WarAxe", type: "Physical" },
  { name: "BladeofDespair", type: "Physical" },
  { name: "SeaHalberd", type: "Physical" },
  { name: "Berserker'sFury", type: "Physical" },
  { name: "Haas'Claws", type: "Physical" },
  { name: "EnchantedTalisman", type: "Magic" },
  { name: "WinterCrown", type: "Magic" },
  { name: "FeatherofHeaven", type: "Magic" },
  { name: "GlowingWand", type: "Magic" },
  { name: "IceQueenWand", type: "Magic" },
  { name: "HolyCrystal", type: "Magic" },
  { name: "FelineBlade", type: "Magic" },
  { name: "PurpleBuff", type: "Magic" },
  { name: "BladeArmor", type: "Defense" },
  { name: "GuardianHelmet", type: "Defense" },
  { name: "AntiqueCuirass", type: "Defense" },
  { name: "Immortality", type: "Defense" },
  { name: "BruteForceBreastplate", type: "Defense" },
  { name: "Oracle", type: "Defense" },
  { name: "DominanceIce", type: "Defense" },
  { name: "Revitalize", type: "Starter" },
  { name: "Aegis", type: "Starter" },
  { name: "Purify", type: "Starter" },
  { name: "Retribution", type: "Starter" },
  { name: "Inspire", type: "Starter" },
  { name: "Claude'sTheft", type: "Special" },
  { name: "KnowledgeCrystal", type: "Special" },
  { name: "GreatDragonSpear", type: "Special" },
  { name: "SkywrathSpear", type: "Special" },
  { name: "HornofProsperity", type: "Special" },
  { name: "SupremeCrown", type: "Special" },
  { name: "Direwolf'sDevastator", type: "Special" },
  { name: "Fluffy'sRage", type: "Special" },
  { name: "Exorcist'sSeal(Basic)", type: "Special" },
  { name: "Exorcist'sSeal(Advanced)", type: "Special" },
  { name: "DauntlessMagicCrystal", type: "Magic Crystal" },
  { name: "SwordsmanMagicCrystal", type: "Magic Crystal" },
  { name: "AstroPowerMagicCrystal", type: "Magic Crystal" },
  { name: "DefenderMagicCrystal", type: "Magic Crystal" },
  { name: "DawnbringerMagicCrystal", type: "Magic Crystal" },
  { name: "EruditioMagicCrystal", type: "Magic Crystal" },
  { name: "WeaponMasterMagicCrystal", type: "Magic Crystal" },
  { name: "NorthernValeMagicCrystal", type: "Magic Crystal" },
  { name: "EmberlordMagicCrystal", type: "Magic Crystal" },
  { name: "MarksmanMagicCrystal", type: "Magic Crystal" },
  { name: "BruiserMagicCrystal", type: "Magic Crystal" },
  { name: "MageMagicCrystal", type: "Magic Crystal" },
  { name: "DragonAltarMagicCrystal", type: "Magic Crystal" },
  { name: "StargazerMagicCrystal", type: "Magic Crystal" },
  { name: "DoomswornMagicCrystal", type: "Magic Crystal" },
];

export interface Synergies {
  name: string;
}

export const Synergy: Synergies[] = [
  { name: "A" },
  { name: "Astro Power" },
  { name: "Bruiser" },
  { name: "Dauntless" },
  { name: "Dawnbringer" },
  { name: "Defender" },
  { name: "Doomsworn" },
  { name: "Dragon Altar" },
  { name: "Emberlord" },
  { name: "Eruditio" },
  { name: "Exorcist" },
  { name: "Faeborn" },
  { name: "Mage" },
  { name: "Marksman" },
  { name: "Northern Vale" },
  { name: "Shadeweaver" },
  { name: "Stargazer" },
  { name: "Summoner" },
  { name: "Support" },
  { name: "Swordsman" },
  { name: "Weapon Master" },
];
