export interface Commanders {
  name: string;
}
export const Commander: Commanders[] = [
  { name: "Aamon" },
  { name: "Abe" },
  { name: "Angela" },
  { name: "Asta" },
  { name: "Aurora" },
  { name: "Bersi" },
  { name: "Brown" },
  { name: "Buss" },
  { name: "Chou" },
  { name: "Connie" },
  { name: "Dubi" },
  { name: "Eggie" },
  { name: "Eva" },
  { name: "Fanny" },
  { name: "Guinevere" },
  { name: "Harper" },
  { name: "Johnson" },
  { name: "Kagura" },
  { name: "Lancelot" },
  { name: "Layla" },
  { name: "Ling" },
  { name: "Lukas" },
  { name: "Lylia" },
  { name: "Mavis" },
  { name: "Miya" },
  { name: "Moskov" },
  { name: "Nana" },
  { name: "Pao" },
  { name: "Popol & Kupa" },
  { name: "Ragnar" },
  { name: "Rya" },
  { name: "Vale" },
  { name: "Wanwan" },
  { name: "Yuki" },
  { name: "Zilong" },
];

export interface Heroes {
  name: string;
  cost: number;
  faction: string;
  role: string;
}

export const Hero: Heroes[] = [
  { name: "Akai", cost: 2, faction: "Dragon Altar", role: "Dauntless" },
  { name: "Aldous", cost: 2, faction: "Dawnbringer", role: "Bruiser" },
  { name: "Alpha", cost: 5, faction: "Shadeweaver", role: "Weapon Master" },
  { name: "Angela", cost: 2, faction: "Faeborn", role: "Mage" },
  { name: "Argus", cost: 4, faction: "Doomsworn", role: "Weapon Master" },
  { name: "Atlas", cost: 1, faction: "Northern Vale", role: "Defender" },
  { name: "Aurora", cost: 5, faction: "Northern Vale", role: "Mage" },
  { name: "Badang", cost: 1, faction: "Emberlord", role: "Bruiser" },
  { name: "Balmond", cost: 2, faction: "Emberlord", role: "Dauntless" },
  { name: "Chang'e", cost: 3, faction: "Dragon Altar", role: "Stargazer" },
  { name: "Clint", cost: 3, faction: "Shadeweaver", role: "Marksman" },
  { name: "Cyclops", cost: 1, faction: "Doomsworn", role: "Stargazer" },
  { name: "Diggie", cost: 2, faction: "Eruditio", role: "Support" },
  { name: "Dyrroth", cost: 3, faction: "Doomsworn", role: "Bruiser" },
  {
    name: "Esmeralda",
    cost: 3,
    faction: "Faeborn",
    role: "Support, Dauntless",
  },
  { name: "Franco", cost: 5, faction: "Doomsworn", role: "Dauntless" },
  { name: "Freya", cost: 3, faction: "Northern Vale", role: "Weapon Master" },
  { name: "Gord", cost: 4, faction: "Emberlord", role: "Mage" },
  { name: "Granger", cost: 2, faction: "Exorcist", role: "Marksman" },
  { name: "Guinevere", cost: 4, faction: "Faeborn", role: "Bruiser" },
  { name: "Gusion", cost: 2, faction: "Dawnbringer", role: "Swordsman" },
  { name: "Hayabusa", cost: 4, faction: "Exorcist", role: "Swordsman" },
  { name: "Helcurt", cost: 1, faction: "Shadeweaver", role: "Swordsman" },
  { name: "Hylos", cost: 2, faction: "Doomsworn", role: "Defender" },
  { name: "Irithel", cost: 4, faction: "Doomsworn", role: "Marksman" },
  { name: "Johnson", cost: 3, faction: "Eruditio", role: "Defender" },
  { name: "Kagura", cost: 3, faction: "Exorcist", role: "Mage" },
  { name: "Kaja", cost: 4, faction: "Emberlord", role: "Defender, Support" },
  { name: "Karina", cost: 3, faction: "Astro Power", role: "Swordsman" },
  { name: "Layla", cost: 2, faction: "Eruditio", role: "Marksman" },
  { name: "Ling", cost: 4, faction: "Dragon Altar", role: "Swordsman" },
  { name: "Lolita", cost: 1, faction: "Eruditio", role: "Dauntless" },
  { name: "Lunox", cost: 4, faction: "Astro Power", role: "Stargazer" },
  { name: "Luo Yi", cost: 2, faction: "Shadeweaver", role: "Stargazer" },
  { name: "Martis", cost: 2, faction: "Astro Power", role: "Weapon Master" },
  { name: "Masha", cost: 2, faction: "Northern Vale", role: "Bruiser" },
  { name: "Minotaur", cost: 5, faction: "Astro Power", role: "Defender" },
  { name: "Moskov", cost: 5, faction: "Emberlord", role: "Marksman" },
  { name: "Natan", cost: 5, faction: "Eruditio", role: "Stargazer" },
  { name: "Nolan", cost: 4, faction: "Eruditio", role: "Swordsman" },
  { name: "Odette", cost: 3, faction: "Astro Power", role: "Mage" },
  { name: "Popol & Kupa", cost: 3, faction: "Northern Vale", role: "Summoner" },
  { name: "Sun", cost: 5, faction: "Dragon Altar", role: "Summoner" },
  { name: "Suyou", cost: 2, faction: "Dragon Altar", role: "Weapon Master" },
  { name: "Terizla", cost: 4, faction: "Dawnbringer", role: "Defender" },
  { name: "Thamuz", cost: 3, faction: "Emberlord", role: "Weapon Master" },
  { name: "Uranus", cost: 3, faction: "Dawnbringer", role: "Dauntless" },
  { name: "Vale", cost: 1, faction: "Dawnbringer", role: "Mage" },
  { name: "Vexana", cost: 4, faction: "Dawnbringer", role: "Summoner" },
  { name: "Wanwan", cost: 1, faction: "Dragon Altar", role: "Marksman" },
  { name: "Yu Zhong", cost: 5, faction: "Exorcist", role: "Bruiser" },
  { name: "Yve", cost: 4, faction: "Northern Vale", role: "Stargazer" },
  { name: "Zhask", cost: 1, faction: "Astro Power", role: "Summoner" },
];

export interface Cards {
  name: string;
  colour: string;
}

export const Card: Cards[] = [
  { name: "Attack & Defend I", colour: "Blue" },
  { name: "Barrier's Seal I", colour: "Blue" },
  { name: "Breath of Berserk I", colour: "Blue" },
  { name: "Cyclical Support", colour: "Blue" },
  { name: "Dark Blade", colour: "Blue" },
  { name: "Excellent Recruit", colour: "Blue" },
  { name: "Glittering Jewels I", colour: "Blue" },
  { name: "Healing Fountain", colour: "Blue" },
  { name: "Heroes Assemble", colour: "Blue" },
  { name: "Jump the Gun", colour: "Blue" },
  { name: "Jump the Gun+", colour: "Blue" },
  { name: "Magic Immersion I", colour: "Blue" },
  { name: "Ocean Treasure", colour: "Blue" },
  { name: "Prime Selection", colour: "Blue" },
  { name: "Purest Power I", colour: "Blue" },
  { name: "Rock Solid", colour: "Blue" },
  { name: "Rogue's Aid", colour: "Blue" },
  { name: "Solid Alliance I", colour: "Blue" },
  { name: "Steady Growth I", colour: "Blue" },
  { name: "Thickened Blood I", colour: "Blue" },
  { name: "Uncertain Fortune", colour: "Blue" },
  { name: "Unlimited Expansion I", colour: "Blue" },
  { name: "Adequate Stock", colour: "Purple" },
  { name: "Airdrop Command", colour: "Purple" },
  { name: "All-around Warrior II", colour: "Purple" },
  { name: "Apex Weapons", colour: "Purple" },
  { name: "Astro Power Badge", colour: "Purple" },
  { name: "Attack & Defend II", colour: "Purple" },
  { name: "Barrier's Seal II", colour: "Purple" },
  { name: "Blood Claw", colour: "Purple" },
  { name: "Bounty Hunt", colour: "Purple" },
  { name: "Breath of Berserk II", colour: "Purple" },
  { name: "Bright Sunshine", colour: "Purple" },
  { name: "Bruiser's Badge", colour: "Purple" },
  { name: "Celestial Embrace", colour: "Purple" },
  { name: "Combat Training I", colour: "Purple" },
  { name: "Coronation", colour: "Purple" },
  { name: "Counteraction", colour: "Purple" },
  { name: "Dawnbringer's Badge", colour: "Purple" },
  { name: "Dauntless' Badge", colour: "Purple" },
  { name: "Defeat's Dividend", colour: "Purple" },
  { name: "Defender's Badge", colour: "Purple" },
  { name: "Demon Commander", colour: "Purple" },
  { name: "Doomsworn's Badge", colour: "Purple" },
  { name: "Dragon Veil", colour: "Purple" },
  { name: "Dragon Altar's Badge", colour: "Purple" },
  { name: "Elite Team", colour: "Purple" },
  { name: "Emberlord's Badge", colour: "Purple" },
  { name: "Enlightenment", colour: "Purple" },
  { name: "Eternal Knowledge", colour: "Purple" },
  { name: "Eternity", colour: "Purple" },
  { name: "Equipment Vault", colour: "Purple" },
  { name: "Eruditio's Badge", colour: "Purple" },
  { name: "Fast Promotion", colour: "Purple" },
  { name: "Fateful Dice", colour: "Purple" },
  { name: "Fortified Defense", colour: "Purple" },
  { name: "Frontier Blitz", colour: "Purple" },
  { name: "Full Throttle", colour: "Purple" },
  { name: "Fully Loaded", colour: "Purple" },
  { name: "Glittering Jewels II", colour: "Purple" },
  { name: "Heroic Arrival", colour: "Purple" },
  { name: "Howling Wind", colour: "Purple" },
  { name: "Leaf & Flower", colour: "Purple" },
  { name: "Magic Immersion II", colour: "Purple" },
  { name: "Magic Surge", colour: "Purple" },
  { name: "Magical Training I", colour: "Purple" },
  { name: "Manic Slam", colour: "Purple" },
  { name: "Marksman's Badge", colour: "Purple" },
  { name: "Northern Vale's Badge", colour: "Purple" },
  { name: "Pas de Deux", colour: "Purple" },
  { name: "Payday", colour: "Purple" },
  { name: "Premium Client I", colour: "Purple" },
  { name: "Purest Power II", colour: "Purple" },
  { name: "Reinforcement", colour: "Purple" },
  { name: "Reinforcement+", colour: "Purple" },
  { name: "Rising Festivities", colour: "Purple" },
  { name: "Rogue Mercenary", colour: "Purple" },
  { name: "Snowstorm", colour: "Purple" },
  { name: "Solid Alliance II", colour: "Purple" },
  { name: "Stargazer's Badge", colour: "Purple" },
  { name: "Steady Growth II", colour: "Purple" },
  { name: "Steel Front", colour: "Purple" },
  { name: "Swordsman's Badge", colour: "Purple" },
  { name: "Talisman Unleashed", colour: "Purple" },
  { name: "Team Mission", colour: "Purple" },
  { name: "Thickened Blood II", colour: "Purple" },
  { name: "The Book of War", colour: "Purple" },
  { name: "Total Domination", colour: "Purple" },
  { name: "Transfer Initiative", colour: "Purple" },
  { name: "Unlimited Expansion II", colour: "Purple" },
  { name: "Unyielding Spirit", colour: "Purple" },
  { name: "Victory Horn II", colour: "Purple" },
  { name: "Weapon Master's Badge", colour: "Purple" },
  { name: "Winner's Mark", colour: "Purple" },
  { name: "Ally's Call", colour: "Orange" },
  { name: "Astro Power's Blessing", colour: "Orange" },
  { name: "Box of Holy Objects", colour: "Orange" },
  { name: "Breath of Berserk III", colour: "Orange" },
  { name: "Bruiser's Blessing", colour: "Orange" },
  { name: "Combat Training II", colour: "Orange" },
  { name: "Dawnbringer's Blessing", colour: "Orange" },
  { name: "Dauntless' Blessing", colour: "Orange" },
  { name: "Defender's Blessing", colour: "Orange" },
  { name: "Doomsworn's Blessing", colour: "Orange" },
  { name: "Dragon Altar's Blessing", colour: "Orange" },
  { name: "Emberlord's Blessing", colour: "Orange" },
  { name: "Ethereal Essence", colour: "Orange" },
  { name: "Eruditio's Blessing", colour: "Orange" },
  { name: "Fortified", colour: "Orange" },
  { name: "Frontline Support", colour: "Orange" },
  { name: "Fully Armed", colour: "Orange" },
  { name: "Golden Era", colour: "Orange" },
  { name: "Golden Era+", colour: "Orange" },
  { name: "Last Resort", colour: "Orange" },
  { name: "Magic Immersion III", colour: "Orange" },
  { name: "Magical Training II", colour: "Orange" },
  { name: "Marksman's Blessing", colour: "Orange" },
  { name: "Novel Equipment", colour: "Orange" },
  { name: "Northern Vale's Blessing", colour: "Orange" },
  { name: "Opening Promotion", colour: "Orange" },
  { name: "Party's Opening", colour: "Orange" },
  { name: "Peculiar Merchant", colour: "Orange" },
  { name: "Premium Client II", colour: "Orange" },
  { name: "Satan's Whisper", colour: "Orange" },
  { name: "Sharp Arrow", colour: "Orange" },
  { name: "Stargazer's Blessing", colour: "Orange" },
  { name: "Strategizing", colour: "Orange" },
  { name: "Surprise Splash", colour: "Orange" },
  { name: "Swordsman's Blessing", colour: "Orange" },
  { name: "Technological Revolution", colour: "Orange" },
  { name: "Technological Revolution+", colour: "Orange" },
  { name: "Territory Agreement", colour: "Orange" },
  { name: "The Hunt", colour: "Orange" },
  { name: "The More, the Merrier", colour: "Orange" },
  { name: "Thickened Blood III", colour: "Orange" },
  { name: "Untamed Soul", colour: "Orange" },
  { name: "Vault Upgrade", colour: "Orange" },
  { name: "Vault Upgrade+", colour: "Orange" },
  { name: "Victory Horn III", colour: "Orange" },
  { name: "Victory Horn III+", colour: "Orange" },
  { name: "Weapon Master's Blessing", colour: "Orange" },
  { name: "Yesterday Once More", colour: "Orange" },
];

export interface Equipments {
  name: string;
  type: string;
}

export const Equipment: Equipments[] = [];
